services:
  - type: web
    plan: free
    name: MD_Rename_Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/moviesdude/MD_Rename_Bot.git       
    branch: main
    envVars:
      - key: TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false 
      - key: CHANNEL
        sync: false
      - key: STRING
        sync: false
      - key: LOG_CHANNEL
        sync: false
    autoDeploy: false
